### ISSUE TITLE
isFirstResponder

### ISSUE THREAD

**Issue by soulshined** [ali312/TLTagsControl#12]
Calling if `([self.tagsControlView isFirstResponder])` in `textFieldDidBeginEditing:` doesn't return anything. I have all my proper delegates assigned in viewDidLoad of the view controller I put the tagsControlView in. What's the proper way to see if the textField in tagsControlView is first responder?

**Comment by AntonKuznetsov** [comment]
Hi @soulshined 

At the moment there is no direct way to see if this textfield it TLTagsControl is firstResponder.
[self.tagsControlView isFirstResponder] returns nothing because tagsControlView is a scroll view an it can't be firstResponder.

I'm going to add  some new delegate methods to the control soon to represent text editing events.

If this is urgent, I can suggest you to create a property of type UITextField in TLTagsControl.h and then set getter of this property to return the tagInputField_ instance variable of TLTagsControl.m

**Comment by soulshined** [comment]
Hey @AntonKuznetsov  sorry that was a typo. I did create a property for the tagInputField_ in the header of your work and nothing happened with first responder. Ultimately as a work around, I just made the view controller I put it in the delegate of that text field by doing self.tagControlView.tagInputField_.delegate = self and handled all the UITextFieldDelegate methods in the view controller since addTag was an instance method in the header already. but i couldn't figure out how to just see if it was first responder. thanks for the hard work though. great piece of work you have here
